### ISSUE TITLE
Rebuild main page 

### ISSUE THREAD

**Issue by AlexKay28** [AlexKay28/langflow#29]
Rebuild the main page such way:
- developers profiles are replaced at the bottom of the page
- Entrance is replaced to the beginning 
- Add an informational panel at the bottom of the page lower than profiles

**Comment by AlexKay28** [comment]
the lower part of the page may look like [this](https://corp.mail.ru/en/company/team/)

**Comment by AlexKay28** [comment]
@Alkhimovmv , I would ask you to discuss this task with Sasha. I hope you remember our last call when we were discussing how the main page should look like =)

**Comment by Alkhimovmv** [comment]
@AlexKay28, I will resolve this issue in the course of [this]([url](https://github.com/AlexKay28/langflow/issues/31)) issue

**Comment by AlexKay28** [comment]
@Alkhimovmv ok. get it

**Comment by AlexKay28** [comment]
seems like #31 was resolved. feel free to reopen issue if it will be actual again
