### ISSUE TITLE
Add validation and messages on login and registration page

### ISSUE THREAD

**Issue by Alkhimovmv** [AlexKay28/langflow#62]

**Comment by AlexKay28** [comment]
@Alkhimovmv  REGISTRATION* page =)

**Comment by Alkhimovmv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add validation and messages on login and registration page](https://trello.com/c/50Dv3jVo/14-add-validation-and-messages-on-login-and-registration-page)
