### ISSUE TITLE
[Fix] Invalid status(Change status in authorization request) 

### ISSUE THREAD

**Issue by Alkhimovmv** [AlexKay28/langflow#97]
[Fix] Invalid status(Change status in authorization request) issue

Current Behavior:
If you register a user with an email and username that is already in the database, in request:
`{
  "message": "Username <111> and/or email <111> already exist", 
  "status": 200
}`

Expected Behavior:
There should be "status": 500

Steps To Reproduce:
Try to register a user with an existing email and username.

Environment:
OS: Ubuntu 20.04
docker: 20.10.12
docker-compose: 1.21.0

**Comment by AlexKay28** [comment]
@Alkhimovmv 
Actually Im not sure that it's a good choice to use code 500. It's not a server error.

I have found this [STACKOWERFLOW_DISCUSSION_LINK](https://stackoverflow.com/questions/9269040/which-http-response-code-for-this-email-is-already-registered/9270432)

Shortly: We need codes 200 or 201. So it just must be an informative message and nothing else. It's not an error.

**Comment by Alkhimovmv** [comment]
@AlexKay28 , maybe in addition to "status: 200" send "error: true" in the request?

**Comment by AlexKay28** [comment]
The most appropriate i guess...

> [7.4.10](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-p2-semantics-18#section-7.4.10).  409 Conflict
> 
>    The request could not be completed due to a conflict with the current
>    state of the resource.  This code is only allowed in situations where
>    it is expected that the user might be able to resolve the conflict
>    and resubmit the request.  The response body SHOULD include enough
>    information for the user to recognize the source of the conflict.
>    Ideally, the response representation would include enough information
>    for the user or user agent to fix the problem; however, that might
>    not be possible and is not required.
> 
>    Conflicts are most likely to occur in response to a PUT request.  For
>    example, if versioning were being used and the representation being
>    PUT included changes to a resource which conflict with those made by
>    an earlier (third-party) request, the server might use the 409
>    response to indicate that it can't complete the request.  In this
>    case, the response representation would likely contain a list of the
>    differences between the two versions in a format defined by the
>    response Content-Type.
